### ISSUE TITLE
Pull emotes from twitch automatically

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#10]
Either pull emotes from twitch itself, or download emotes on server start. I'm thinking that having a json file of accepted channels in chat could work the best since it could be too much to search all channels on twitch.

Twitch emote api docs: https://www.twitchemotes.com/apidocs

**Comment by zorchenhimer** [comment]
The v3 API on twitchemotes.com is no longer being updated, so `/addemotes` is half broken now.

**Comment by zorchenhimer** [comment]
This was merged in with 54377c6 but never closed.
