### ISSUE TITLE
Unable to join chat (join is not a function)

### ISSUE THREAD

**Issue by techlover1** [zorchenhimer/MovieNight#101]
When attempting to join the chat nothing happens. In JS console I get the error: `Uncaught TypeError: join is not a function
    at HTMLInputElement.onclick ((index):119)`

System is running a fresh install of Kubuntu 19.10, accessing from lan with no reverse proxy

Console log is attached

[10.16.20.120-1574973303813.log](https://github.com/zorchenhimer/MovieNight/files/3902994/10.16.20.120-1574973303813.log)

**Comment by zorchenhimer** [comment]
What version of Go are you running?  It sounds like `static/js/wasm_exec.js` is for a different version of Go than you compiled with.  I still don't have a good way to automatically grab the correct version, but you should be able to find it at `/usr/lib/go/misc/wasm/wasm_exec.js` (see #97).

You should be able to just copy the file from Go's directory into the `static/js/` directory and be all set.

**Comment by techlover1** [comment]
Running go 1.12.10
Copying the file worked. However, now when I send a message it shows in the console, but not in the browser

**Comment by zorchenhimer** [comment]
That was a bug that I fixed the other day with 78ecee1.  Pull the changes, and that should fix it. (it's a CSS change so you may need to ctrl-f5 to get the new version in your browser)

**Comment by techlover1** [comment]
Awesome! That did it, Thanks!
