### ISSUE TITLE
Chat doesn't work when building with Go 1.14

### ISSUE THREAD

**Issue by ulope** [zorchenhimer/MovieNight#106]
When building with Go 1.14 the chat doesn't load (stuck at "Loading Files").

The browser console shows the following error:
```
chat.js:53 LinkError: WebAssembly.instantiate(): Import #1 module="go" function="runtime.resetMemoryDataView" error: function import requires a callable
```

Rebuilding with 1.13 makes it work as expected.

**Comment by zorchenhimer** [comment]
Try pulling the latest.  A PR was merged that should fix this.  (run `make clean` first)
