### ISSUE TITLE
[Suggestion] Flag for Admin Password

### ISSUE THREAD

**Issue by therealchaudhri** [zorchenhimer/MovieNight#112]
Hey, I know that this is present in the settings json file, but is it possible to add a switch, lets say `-p`, such that running `./MovieNight -p MyAmazingPassword` would start the client with the appropriate admin password?

**Comment by therealchaudhri** [comment]
Update: As of now, MovieNight completely disregards any manual input of the Administrator Password in the settings.json file as well. This poses a problem for certain use cases, such as when one is unable to capture console output.

**Comment by zorchenhimer** [comment]
The password is written to the config file on startup.  This was done so I didn't have to watch the console output to get it.  There isn't a way to set the password yet, but I'm not against adding it as a command line option.

**Comment by zorchenhimer** [comment]
I had a look and this was easy enough to add (commit ce2150f7192807fc731b0c2766313ae9836920cb).  The command line switch is `-a` instead of `-p`, as I might add another option to specify a moderator password later.  A password set this way will not be written to the configuration file.
