### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by Aphris-Karu** [zorchenhimer/MovieNight#113]
Just finished a COVID Movie night stream for the family. Looking over the metrics there may be a memory leak.

I brought the container up in the swarm 1hr before the stream started and just let it run. No stream and no one connected to it, just to get a baseline of usage and noticed the memory climbing.

![MovieNight-Monitoring-1hr-idol-server](https://user-images.githubusercontent.com/46301934/80167338-c508ae80-85a5-11ea-9b86-9ea56677e92a.png)

Once the stream started we had 6 people in chat and I know of 2 others that were watching but not in chat. The stats for the 2 hour movie are below. Should give others an idea as to how many resources are used for streaming out to 8 people.

![MovieNight-Monitoring-full-2hr-stream](https://user-images.githubusercontent.com/46301934/80167552-46f8d780-85a6-11ea-8c10-46520a217ea3.png)

You may note that while CPU, and Network utilization dropped off at the end. Memory usage did not.

Personally I was surprised at how 8 people only used 3mbps of network bandwidth.

**Comment by zorchenhimer** [comment]
Hmm, yea, that looks like a leak to me.  I'll see if I can narrow down where it is.  Was the server completely idle during the first hour?  Were you connected to chat with the webpage open?

**Comment by Aphris-Karu** [comment]
I was not connected to chat or the web interface. So it was completely idle.

**Comment by zorchenhimer** [comment]
Alright, I tried reproducing this by leaving an instance running over night and another instance for about an hour today and I cannot reproduce it.

What else is running in the container and can you confirm that MovieNight is actually taking that memory?

**Comment by Aphris-Karu** [comment]
It is the only thing running in the container but it is an older version. Ill update and see if it is fixed.

**Comment by Aphris-Karu** [comment]
Looks like the memory leak is gone on the newest version.

**Comment by zorchenhimer** [comment]
Huh, nothing really changed recently that would change that.  The only thing that's been reworked is the emote parsing, but that shouldn't be running regardless if there are no messages to parse.
