### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by dusk125** [zorchenhimer/MovieNight#132]
I was working on something similar (streaming rtmp to a webpage without the use of HLS/Dash), I was in the experimental stage and hadn't gotten flv.js to work and came across this project. I'm working on a streaming stack for a charity livestream event (called Love Tropics) and I would love to use the streaming part of the project; I looked for a license here but didn't see one. If you'd prefer to decline, that's completely understandable and I'll figure it out another way, I thought I would ask to keep me from reinventing the wheel.

**Comment by zorchenhimer** [comment]
I have no problem with you using the code in this project.

I've been meaning to add a license to this project for a while and finally got around to it with fd95fa7.

**Comment by dusk125** [comment]
Thank you.
