### ISSUE TITLE
Show timestamp is not working when it is saved

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MovieNight#133]
A few movienights ago i set the show timestamp option but in todays movienight i had to disable and reenable the option to get the timestamps displayed in the chat.

![image](https://user-images.githubusercontent.com/23438606/87234729-449f6000-c3d4-11ea-92aa-35d158f4fa10.png)
Before and after reenabling show timestamp.

Further Information:
The checkmark on show timestamp was set but the timestamps did not get displayed until resetting the option.

Browser: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by zorglube** [comment]
It seems that this feature is still here and working.
