### ISSUE TITLE
Server freezes when incorrect stream key used

### ISSUE THREAD

**Issue by Bruno-DaSilva** [zorchenhimer/MovieNight#146]
It seems when someone includes a bad stream key the whole app freezes and needs to be restarted.

I _think_ this might be related to the lack of unlock before return on https://github.com/zorchenhimer/MovieNight/blob/master/handlers.go#L376.

Is it safe to add a `l.Unlock()` before this return? Not sure if there's some side effects of simply returning to deny a stream.

**Comment by Bruno-DaSilva** [comment]
See https://github.com/zorchenhimer/MovieNight/pull/147

**Comment by Bruno-DaSilva** [comment]
Confirmed that the patch errors with incorrect stream keys while no longer freezing the app. I'm assuming it works for the other error cases there as well.

**Comment by zorchenhimer** [comment]
Should be all set now.
