### ISSUE TITLE
joy4 is deprecated

### ISSUE THREAD

**Issue by hoehermann** [zorchenhimer/MovieNight#152]
MovieNight is depending on joy4 which seems to be [abandoned](https://github.com/nareix/joy4/issues/89) and cannot be built on Ubuntu 20.04:

    # github.com/nareix/joy4/codec/h264parser
    vet: go/pkg/mod/github.com/nareix/joy4@v0.0.0-20200507095837-05a4ffbb5369/codec/h264parser/parser_test.go:13:14: cannot use SplitNALUs(annexbFrame) (value of type int) as bool value in assignment
    # github.com/nareix/joy4/format/mp4/mp4io/gen
    vet: go/pkg/mod/github.com/nareix/joy4@v0.0.0-20200507095837-05a4ffbb5369/format/mp4/mp4io/gen/pattern.go:411:8: undeclared name: Version
    # github.com/nareix/joy4/format/rtsp/sdp
    vet: go/pkg/mod/github.com/nareix/joy4@v0.0.0-20200507095837-05a4ffbb5369/format/rtsp/sdp/parser_test.go:8:11: undeclared name: Decode
    # github.com/nareix/joy4/utils/bits
    vet: go/pkg/mod/github.com/nareix/joy4@v0.0.0-20200507095837-05a4ffbb5369/utils/bits/bits_test.go:47:2: undeclared name: PutUInt64BE
    # github.com/nareix/joy4/utils/bits/pio
    go/pkg/mod/github.com/nareix/joy4@v0.0.0-20200507095837-05a4ffbb5369/utils/bits/pio/vec_test.go:7:1: ExampleVec refers to unknown identifier: Vec

Are there any plans to move to joy5?

**Comment by zorglube** [comment]
Certainly, you can submit an PR.

**Comment by zorchenhimer** [comment]
The last time joy5 was updated two month's after the last commit in joy4, so that one's not exactly "active" either.  Even if I wanted to use joy5, the documentation is non-existent and last I checked the API changed.

I haven't had any issue building.  What is your Go version?

**Comment by hoehermann** [comment]
Thank you for the reply. I am using `go version go1.13.8 linux/amd6` on `Ubuntu 20.04.2 LTS` (I just upgraded to this release). Trying to build via `GOPATH=$(pwd)/go make TARGET=linux ARCH=amd64`. Packages `libavformat-dev libavresample-dev libswscale-dev` are installed. No other libraries were reported to be missing.

**Comment by zorchenhimer** [comment]
I went and grabbed 20.04 LTS and spun it up in a VM and I'm getting a different error when trying the command you're running to build.

Is there a reason you're relocating `GOPATH`?  If I just run `make` without redirecting stuff i get a build just fine (including cross-compiling):

![image](https://user-images.githubusercontent.com/6540297/110254092-a1e7b300-7f5b-11eb-93c5-c2929601d632.png)

**Comment by hoehermann** [comment]
I was told using one GOPATH per project was is considered good practice. Apparently, I have been mistaken. My bad.

**Comment by zorchenhimer** [comment]
No worries!  It may have been something to do before modules were a thing, but it shouldn't be needed anymore.
