### ISSUE TITLE
How do I play a local file?

### ISSUE THREAD

**Issue by polkunus** [zorchenhimer/MovieNight#159]

**Comment by zorglube** [comment]
I would say, MovieNight isn't a player, but I may have missed something. @zorchenhimer do you confirm?

**Comment by CptPie** [comment]
Heyo @polkunus,
what exactly do you mean with a "local" file? The basic idea of MovieNight is to have some system stream to the MovieNight server (via rtmp) and the server itself just distributes that stream. Hence there is no need to upload any files to the server running the MovieNight service. For the "i have the file on the server and want to distribute that"-usecase there are other projects that work in that way.

**Comment by zorglube** [comment]
Think it's time to close this issue ?
