### ISSUE TITLE
Custom images as emotes

### ISSUE THREAD

**Issue by Your-New-SJW-Waifu** [zorchenhimer/MovieNight#160]
Is there a way to just add my own images for use as emotes?

**Comment by zorchenhimer** [comment]
Absolutely! Just drop png, jpg, or gif files into the `static/emotes` folder. The filename, minus the extension, will be its name to use in chat.

**Comment by Your-New-SJW-Waifu** [comment]
Oh, okay. I was wondering if it was that easy or I needed to write some JSON map or something. Plan to put like 7.5k in there then. 
Might be worth saying you can do that in the readme.

**Comment by zorchenhimer** [comment]
Correction: apparently JPG images aren't filtered.  Only PNG and GIF images are used (see [here](https://github.com/zorchenhimer/MovieNight/blob/3396761efeabb0826e6d5eaf5447b35b8814647e/emotes.go#L132)).

As for SVG's, there isn't anything stopping those from being supported on the server side.  I'm not sure how well the different browsers support them though.

**Comment by Your-New-SJW-Waifu** [comment]
Ah, okay, thanks for the heads up. Virtually every web browser that can display images should be able to handle SVGs. 

Also, it doesn't seem to like `<` and `>`.  In the filename.
e.g.  >.<.png

I suspect that has to do with url encoding and the server not properly interpreting a request for https://host.tld/emotes/%3e.%3c.png as a request for >.<.png 

I can open that into it's own issue if you'd like.

**Comment by zorchenhimer** [comment]
Hmm, i suppose the easiest way to solve that would be to URL-encode all the emote filenames as they're loaded.  Feel free to open an issue if you want.
