### ISSUE TITLE
VOD recording

### ISSUE THREAD

**Issue by Waffleuncle** [zorchenhimer/MovieNight#162]
Is it possible to have the VOD recordings

**Comment by zorchenhimer** [comment]
VODs and making clips is out of scope for this project.  While it would be possible to save the RTMP stream to disk, it would probably need to be transcoded before it's able to be played.

**Comment by CptPie** [comment]
One other option (depending on your setup):
When using OBS you can both stream and record the scene at the same time (although it will probably skyrocket the cpu/gpu usage).

**Comment by zorglube** [comment]
Are you sure it is the responsibility of the broadcast relay to record the stream datas ?
