### ISSUE TITLE
Fix linting errors because I'm slowly going insane from seeing them all the time

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#174]
Fix them
![image](https://user-images.githubusercontent.com/27922090/157355035-d69921d6-6846-41de-9064-f549dd46c2b9.png)

**Comment by CptPie** [comment]
In conjunction it might also be useful to come up with a (selection?) of linters that we want to use (best case having the same linters for both movienight and polls)

**Comment by joeyak** [comment]
Yep I was thinking that. After I'm done working on #172 I want to at least run the 4 different linters here and see what they say and compare returns.
![image](https://user-images.githubusercontent.com/27922090/157498248-acff8cac-ab33-4dac-9d2f-7304cb15502f.png)
