### ISSUE TITLE
Move code in ./common into the main directory?

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#177]
Now that wasm is being removed in https://github.com/zorchenhimer/MovieNight/issues/168 we can move the code in `common` out because it's not longer being used. Now an alternative to that is leave it in common because it does break up the code somewhat into smaller sections.

**Comment by CptPie** [comment]
Speaking from my own (biased) opinion/experience with moviepolls, i would try to keep your main directory as "clean" as possible, basically only having the main.go, buildfiles and other stuff (linter config) in the main dir.

**Comment by joeyak** [comment]
hmm good point. Maybe we need to restructure the root directory a bit more? One thing I definitely want to do is combine `emotes.go` and `common/emotes.go`

**Comment by zorglube** [comment]
Il vote for @CptPie point of view ! (Whatever worth my vote 🤣).

**Comment by joeyak** [comment]
common/emotes was combined into emotes.go with the embed branch
