### ISSUE TITLE
emotes bug

### ISSUE THREAD

**Issue by TOWUK** [zorchenhimer/MovieNight#194]
![image](https://user-images.githubusercontent.com/28830162/215350414-a00fd1dd-e95c-4b4c-acaf-f41c316d26bb.png)

**Comment by TOWUK** [comment]
win 11 64 bit / latest go / latest git

**Comment by zorchenhimer** [comment]
Emotes aren't included in the repo, you'll have to provide your own.  The error could be a bit more descriptive, but this isn't a bug.
