### ISSUE TITLE
Add *user is typing* notifications like on rabbit and discord

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#36]

**Comment by joeyak** [comment]
Like this 
![image](https://user-images.githubusercontent.com/27922090/54478707-9db0b100-47eb-11e9-95b3-dbfc5e9a57c3.png)

**Comment by zorchenhimer** [comment]
This would be fine as long as it's configurable.  Maybe three levels?

- Off
- "somebody is typing"
- "{name} is typing"

**Comment by joeyak** [comment]
I actually like the idea of the three levels. The one thing I liked about rabb.it doing is showing me that a message is comming. It's a minor thing, but it means that you have a heads up to read a response.

**Comment by joeyak** [comment]
After some discussion with @zorchenhimer I have decided to self veto.

The biggest issue I see with this is the posibility of "spamming" data to and from the server. With a couple clients it should be fine, but with more connections, the more "extra" data is being sent to the server. The heartbeat was a fine for fixing issue #35, but that was only a 10 second interval with no response from the server.
