### ISSUE TITLE
Add some logging levels

### ISSUE THREAD

**Issue by zorchenhimer** [zorchenhimer/MovieNight#46]
Add some log levels.  Specifically, only print errors by default and not all the things that are being done (eg, `[static] serving "js/both.js" from folder ./static/`).

This should be configurable and have more than one level available:

- Debug/verbose (print everything)
- Just chat and start/stop stream
- Only errors

Optionally, the log should write to a file and should be configurable from the settings.  I don't think this is something that needs a command, but I'm not opposed to adding one to change logging levels.

**Comment by joeyak** [comment]
So we have a very large list of possible loggers to use on [awesome-go](https://github.com/avelino/awesome-go#logging), and there is also the standard library logging library [log](https://golang.org/pkg/log/).

We might be able to create different [loggers](https://golang.org/pkg/log/#Logger) each with a separate prefix, and have a custom logger wrapping class. Sadly log only has `Print[f|ln], Fatal[f|ln], and Panic[f|ln]` so there isn't any functions like `Debug(), Info(), Error()`.

**Comment by zorchenhimer** [comment]
I'd rather have our own `Debug()`, `Info()`, and `Error()` functions that each check for their logging level and write to the log file.  Note that there will only be a single logger as there should only be a single log file.

Additionally, anything written to the log file should be written to the console, via `io.MultiWriter()`.

As for their function signatures, I'm thinking mimic `fmt.Printf()`.  Eg, `Debug(format string, a ...interface{})`
