### ISSUE TITLE
A user cannot rejoin the room after leaving

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#52]
When a user leaves a room, and tries to re-enter, the name says it's taken. This seemed to happen after https://github.com/zorchenhimer/MovieNight/commit/1c6c23da3e8fc88204e528db01cec5051a94d99a
![image](https://user-images.githubusercontent.com/27922090/54657862-74b94600-4aa1-11e9-8da8-0a7f7ffb90c7.png)

**Comment by zorchenhimer** [comment]
Define "leaving".  Does the user reload the page, or does the server restart?

For server restarts, the websocket connection closes and isn't reopened when the server comes back up.

**Comment by joeyak** [comment]
This occured when I refreshed the page.

**Comment by joeyak** [comment]
I found it when I would change css, hit f5, and try to join with the same username
