### ISSUE TITLE
MovieNight: command not found

### ISSUE THREAD

**Issue by daicain** [zorchenhimer/MovieNight#54]
I followed the simple guide on how to install MovieNight and when I went to start the server, I got **

> MovieNight: command not found

**

**Comment by joeyak** [comment]
Could you give us some more information about your operating system and the output of `go get -u -v github.com/zorchenhimer/MovieNight`. Also check if your GOPATH is in your path.

I ran the command on a Windows 10 machine after deleting both the executable in `GOPATH\bin` and the directory `GOPATH\src\github.com\zorchenhimer\MovieNight`

**Comment by daicain** [comment]
Oh Sorry I am running this on Ubuntu 18 x64

**Comment by zorchenhimer** [comment]
It sounds like Go's `bin` directory isn't in your `$PATH`.  Do either of these work for you?

```bash
$ cd $HOME/go/bin
$ ./MovieNight
```
or
```bash
$ cd $GOPATH/bin
$ ./MovieNight
```

**Comment by zorchenhimer** [comment]
This should be fixed with the recent Go module updates.
