### ISSUE TITLE
Add more command buttons

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#55]
Add command buttons for all the commands, and have it hide and split by auth levels.

**Comment by joeyak** [comment]
I decided not to add the buttons for mod and admin commands. The help page hides stuff depending on if the user is an admin or mod. I also didn't implement the other commands like users and count because it doesn't need prompting.

**Comment by joeyak** [comment]
Now that there is some underlying framework added in cd34480bba7c33e7ffff4e25ab41aa690f849dc1, I am reopening it

**Comment by zorchenhimer** [comment]
Closing this as I think we've got the important ones as buttons.  I don't want to add mod or admin commands as buttons at this time.
