### ISSUE TITLE
Add a way to tell the client if it is admin or mod

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#60]
Make this a hidden message. This is so the client can decide which buttons to render and any other decisions if needed.

**Comment by zorchenhimer** [comment]
There are admin and mod badges in chat already.  Do you mean something else?

**Comment by joeyak** [comment]
Added to description. I mean programmatically so the client code can do some rendering based on if the user is an admin or not.  I think there would be no harm in having the admin and mod commands be inside the html, and this would be the first step to adding it.

We could use the "/whoami" command and parse that, but I would rather have an object that is deserialized like the rest of the objects are.
