### ISSUE TITLE
Add spoilers in chat

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#62]
Add a spoiler command.
Invokation "/sp", "/spoiler"

It will output a tag that has a grey view over it, when clicked the covering part will disapear. have in lgiht letters spoiler over the grey view.

**Comment by zorchenhimer** [comment]
How about mimicking Discord's syntax?  `||spoiler here||` instead of making the whole message a spoiler.

**Comment by joeyak** [comment]
I like that better actually. Then it can just be a split and insert
