### ISSUE TITLE
Don't allow clients to repeat a message

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#65]
The server will keep track of the last message a client sent, and if it is the same, it will send a message like "You cannot send the same message in a row"

**Comment by zorchenhimer** [comment]
I'd like to expand this into a more general rate-limiting scheme.

For example, a client will not be allowed to same the same message as the previous, if the previous was less than ~30 seconds ago.  As well as a one second cooldown per client (client cannot send messages faster than 1msg/sec).

**Comment by joeyak** [comment]
I agree with the expansion. But admins should not be rate limited, maybe even mods. What do you think on mods being rate limited?

**Comment by zorchenhimer** [comment]
Mods and admins already have exceptions to a bunch of commands and functionality (eg, links in chat), so I think it's within reason that they would also be exempt from rate-limiting.

**Comment by zorchenhimer** [comment]
To add onto this, things like changing your display name should be on a longer cooldown. Something like five minutes by default.
