### ISSUE TITLE
Add custom command message type for command returns

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#71]
So, when an error occurs in a command, a string saying a message to the client is sent. Now that communication is done via objects, the client could be handed an error object too, and have more customization.

**Comment by zorchenhimer** [comment]
This has been partially implemented in 5508dc3f.  Instead of returning a new object, the command functions return `(string, error)`.

**Comment by zorchenhimer** [comment]
This was completed with 81e647c.
