### ISSUE TITLE
Make default option in suggestions the bottom one, not the top

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#86]

**Comment by joeyak** [comment]
Also put cheers on the bottom

**Comment by zorchenhimer** [comment]
Cheers aren't handled any differently than normal emotes.  They're just named with "cheer".

**Comment by joeyak** [comment]
Yeah, after thinking on it more, it wouldn't be a good idea to sort by name `cheer` on the bottom
