### ISSUE TITLE
A more in-depth documentation for noobs?

### ISSUE THREAD

**Issue by daicain** [zorchenhimer/MovieNight#87]
Would it be possible to add more detailed documentation for noobs?
I used a fresh Ubuntu VM and installed Make and Go 1.12.2 but still cannot get this to run.
I'm probably missing a few steps, like where to download MovieNight or setting up Go Paths?

I basically just installed Make, Go, downloaded MovieNight, ran "make get" inside MovieNight folder and got an error about make 'get' not able to find the recipe.

**Comment by zorchenhimer** [comment]
If you've installed Go using [these instructions](https://golang.org/doc/install#tarball), you'll need to add something like this to the bottom of your `~/.bashrc` file:

```bash
export PATH=$PATH:/usr/local/go/bin:/home/YOUR_USERNAME/go/bin
```

Then from the MovieNight folder run `make get` again for good measure and then `make`.

I just tried on a fresh install of Ubuntu and you may need to also install `gcc` as some dependencies use cgo.

**Comment by daicain** [comment]
Okay so I got 1 step further. I am able to do` make get` , but when I do `make `, here's the error:

```
root@Test:~/MovieNight# make
goimports -w .
make: goimports: Command not found
Makefile:25: recipe for target 'fmt' failed
make: *** [fmt] Error 127
```

**Comment by zorchenhimer** [comment]
Looks like you still do not have your path setup correctly.  Note that there are two directories being added to it: `/usr/local/go/bin` as well as `/home/YOUR_USERNAME/go/bin`.  Don't forget to change `YOUR_USERNAME` to the account username you are using.

**Comment by daicain** [comment]
I finally got it to work, thank you. Here are all the steps I took on a fresh Ubuntu 18.10 x64 for anyone else not as experience in Linux as I am...

1. `sudo apt-get update && sudo apt-get upgrade -y` 
2. `sudo apt-get install build-essential` - for `make `and stuff
3. Using [These Instructions](https://golang.org/doc/install#tarball) I install go1.12.4.linux-amd64.tar.gz
4. `wget https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz`
5. ` tar -C /usr/local -xzf go1.12.4.linux-amd64.tar.gz`
6. `export PATH=$PATH:/usr/local/go/bin`
7. Added `export PATH=$PATH:/usr/local/go/bin:/root/go/bin` to the bottom of my `~/.bashrc` file.
8. `sudo reboot` just for good measure
9. `git clone https://github.com/zorchenhimer/MovieNight` - (current dir is /root)
10. `cd MovieNight`
11. `make get`
12. `make`
13. `./MovieNight`

**Comment by zorchenhimer** [comment]
Glad to hear!

Quick thing I'd like to point out though.  You mention your current directory is `/root` in step 9.  I would recommend against running as root.  Is usually bad practice to run a lot of stuff as root, and the default port isn't low enough that it requires root permissions to bind to.

**Comment by daicain** [comment]
> Glad to hear!
> 
> Quick thing I'd like to point out though. You mention your current directory is `/root` in step 9. I would recommend against running as root. Is usually bad practice to run a lot of stuff as root, and the default port isn't low enough that it requires root permissions to bind to.

Yeah, this was just a quick test from scratch to make sure it works. For anyone else, please don't do this on root!
