### ISSUE TITLE
Feature by saving stream and chat history

### ISSUE THREAD

**Issue by menvol3** [zorchenhimer/MovieNight#92]
Hi, is it possible to add features like saving the stream in .mp4 or .flv format and chat history ?

**Comment by zorchenhimer** [comment]
Chat history is already dumped to the log file (if the correct logging level is set).  Saving the stream video is a different story.  That was never really an aim for the project, but it *might* be possible.

The server does no transcoding whatsoever.  It just reads the incoming stream, and copies it to each client.  Before saving any of that to disk, I would want transcoding implemented (eg. RTMP -> HLS).

**Comment by zorchenhimer** [comment]
Closing this as out-of-scope.
