### ISSUE TITLE
Include minimum system requirements in README

### ISSUE THREAD

**Issue by voidpls** [zorchenhimer/MovieNight#93]
Give an estimated resource usage stat for X users in README.md. Ex:

10 concurrent watchers:
Min: 1cpu 1gb
Rec: 2cpu 2gb

25 concurrent watchers:
Min: 2cpu 2.5gb
Rec: 4cpu 4gb

**Comment by zorchenhimer** [comment]
Not gonna lie, I have no idea what the requirements would be.  The VPS I use this on has 1gb ram and two cores and has handled up to ~30 viewers.  You'll probably hit a networking bottleneck first.

**Comment by joeyak** [comment]
Yeah, either the bottleneck will be on the clients computer with the wasm/JavaScript or on the network. Way back, I tried load testing with zorchs server, and I had over 100 connections before we ran out of threads, which was a hard limit. And this was before message timeouts were added.

**Comment by docwho76** [comment]
The real bottleneck is network based, CPU-wise this thing is nothing, I've run this on a1.mediums in AWS just fine.

**Comment by zorchenhimer** [comment]
I've had someone in in my community run it successfully on a Raspberry Pi Zero W.  If it has an OS with and an internet connection, it'll probably work just fine.
